nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

packageExtensions:
  "gts@*":
    dependencies:
      "eslint": "^8.57.0"
